*** Variables ***
${PROFILE_LOGIN_BTN}    ru.afisha.android:id/itemLoginBtn
${PROFILE_SOCIAL_BTN}    ru.afisha.android:id/socialButton
${PROFILE_LOGIN_TO_REGISTER}    //android.view.View[@content-desc="Регистрация"]
${PROFILE_REGISTERED_TEXT}    //android.view.View[@content-desc="Я уже зарегистрирован"]
${PROFILE_EMAIL_FIELD}    //android.widget.EditText[@index=0]
${PROFILE_PASSWORD_FIELD}    //android.widget.EditText[@index=1]
${PROFILE_CONFIRM_REGISTRATION}     //android.widget.Button[@text="Зарегистрироваться"]
${PROFILE_REGISTRATION_COMPLETE}    //android.widget.TextView[@text="Завершение регистрации"]